name: Codeward-io Scan
description: Scan action by codeward-io
inputs:
  event:
    description: 'Event name'
    required: true
    type: string
    default: ${{ github.event_name }}
  repository:
    description: 'Repository'
    required: true
    type: string
    default: ${{ github.repository }}
  current_branch:
    description: 'Current branch'
    required: true
    type: string
    default: ${{ github.ref }}
  pr_number:
    description: 'Pull request number'
    required: false
    type: string
    default: ${{ github.event.number }}
  token:
    description: 'Github token'
    required: true
    type: string
    default: ${{ github.token }}
runs:
  using: composite
  steps:
    - name: Checkout branch
      if: ${{ inputs.event == 'pull_request' }}
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.current_branch }}
        repository: ${{ inputs.repository }}
        path: branch

    - name: Checkout base
      uses: actions/checkout@v4
      with:
        ref: ${{ github.BASE_REF }}
        repository: ${{ inputs.repository }}
        path: main

    - name: Pull Codeward scan image
      shell: bash
      run: |
        docker login ghcr.io -u ${{ github.actor }} -p ${{ inputs.token }}
        docker pull ghcr.io/codeward-io/scan:v0.2.0
  
    - name: Create local storage
      shell: bash
      run: |
        mkdir -p results
        mkdir -p cache

    - name: Run scanner with branch
      if: ${{ inputs.event == 'pull_request' }}
      shell: bash
      run: |
        docker run --rm --name codeward-scan \
        -v ${PWD}/main:/main:rw \
        -v ${PWD}/branch:/branch:rw \
        -v ${PWD}/results:/results:rw \
        -v ${PWD}/cache:/tmp/.cache:rw \
        --user ${UID} \
        -e CODEWARD_GITHUB_TOKEN=${{ inputs.token }} \
        -e CODEWARD_GITHUB_OWNER=${{ github.repository_owner }} \
        -e CODEWARD_GITHUB_REPOSITORY=${{ github.event.repository.name }} \
        -e CODEWARD_GITHUB_PR_NUMBER=${{ inputs.pr_number }} \
        -e CODEWARD_MODE="diff" \
        ghcr.io/codeward-io/scan:v0.2.0

    - name: Run scanner without branch
      if: ${{ inputs.event != 'pull_request' }}
      shell: bash
      run: |
        docker run --rm --name codeward-scan \
        -v ${PWD}/main:/main:rw \
        -v ${PWD}/results:/results:rw \
        -v ${PWD}/cache:/tmp/.cache:rw \
        --user ${UID} \
        -e CODEWARD_GITHUB_TOKEN=${{ inputs.token }} \
        -e CODEWARD_GITHUB_OWNER=${{ github.repository_owner }} \
        -e CODEWARD_GITHUB_REPOSITORY=${{ github.event.repository.name }} \
        -e CODEWARD_MODE="main" \
        ghcr.io/codeward-io/scan:v0.2.0
